title: Site
preset: page
unlisted: true
fields:
  description:
    label: Website Description
    type: textarea
  instagram:
    label: Instagram
    type: text
    width: 1/2
  email:
    label: Email
    type: text
    width: 1/2
